name: .NET Core

on: [push, pull_request]

jobs:
  dotnet:
    name: ${{ matrix.framework-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        framework-version: [net7.0, net6.0, net5.0, netcoreapp3.1]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            5.0.x
            3.1.x

      - name: Tests
        run: dotnet test -c Release -f ${{ matrix.framework-version }}
